// Generated by CoffeeScript 1.6.2
(function() {
  var root, u, _base,
    __hasProp = {}.hasOwnProperty,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __slice = [].slice,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.ABM = {};

  root = this;

  (function() {
    var vendor, _i, _len, _ref;

    this.requestAnimFrame = this.requestAnimationFrame || null;
    this.cancelAnimFrame = this.cancelAnimationFrame || null;
    _ref = ['ms', 'moz', 'webkit', 'o'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      vendor = _ref[_i];
      if (!(!this.requestAnimFrame)) {
        continue;
      }
      this.requestAnimFrame || (this.requestAnimFrame = this[vendor + 'RequestAnimationFrame']);
      this.cancelAnimFrame || (this.cancelAnimFrame = this[vendor + 'CancelAnimationFrame']);
      this.cancelAnimFrame || (this.cancelAnimFrame = this[vendor + 'CancelRequestAnimationFrame']);
    }
    this.requestAnimFrame || (this.requestAnimFrame = function(callback) {
      return this.setTimeout(callback, 1000 / 60);
    });
    return this.cancelAnimFrame || (this.cancelAnimFrame = function(id) {
      return this.clearTimeout(id);
    });
  })();

  (_base = Array.prototype).indexOf || (_base.indexOf = function(item) {
    var i, x, _i, _len;

    for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
      x = this[i];
      if (x === item) {
        return i;
      }
    }
    return -1;
  });

  ABM.util = u = {
    error: function(s) {
      throw new Error(s);
    },
    isArray: Array.isArray || function(obj) {
      return !!(obj && obj.concat && obj.unshift && !obj.callee);
    },
    isFunction: function(obj) {
      return !!(obj && obj.constructor && obj.call && obj.apply);
    },
    isString: function(obj) {
      return !!(obj === '' || (obj && obj.charCodeAt && obj.substr));
    },
    randomInt: function(max) {
      return Math.floor(Math.random() * max);
    },
    randomInt2: function(min, max) {
      return min + Math.floor(Math.random() * (max - min));
    },
    randomFloat: function(max) {
      return Math.random() * max;
    },
    randomFloat2: function(min, max) {
      return min + Math.random() * (max - min);
    },
    randomCentered: function(r) {
      return this.randomFloat2(-r / 2, r / 2);
    },
    log10: function(n) {
      return Math.log(n) / Math.LN10;
    },
    logN: function(n, base) {
      return Math.log(n) / Math.log(base);
    },
    ln: function(n) {
      return Math.log(n);
    },
    mod: function(v, n) {
      return ((v % n) + n) % n;
    },
    wrap: function(v, min, max) {
      return min + this.mod(v - min, max - min);
    },
    clamp: function(v, min, max) {
      return Math.max(Math.min(v, max), min);
    },
    sign: function(v) {
      return (v < 0 ? -1 : 1);
    },
    aToFixed: function(a, p, s) {
      var i;

      if (p == null) {
        p = 2;
      }
      if (s == null) {
        s = ", ";
      }
      return "[" + (((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = a.length; _i < _len; _i++) {
          i = a[_i];
          _results.push(i.toFixed(p));
        }
        return _results;
      })()).join(s)) + "]";
    },
    randomColor: function(c) {
      var i, _i;

      if (c == null) {
        c = [];
      }
      if (c.str != null) {
        c.str = null;
      }
      for (i = _i = 0; _i <= 2; i = ++_i) {
        c[i] = this.randomInt(256);
      }
      return c;
    },
    randomGray: function(c, min, max) {
      var i, r, _i;

      if (c == null) {
        c = [];
      }
      if (min == null) {
        min = 64;
      }
      if (max == null) {
        max = 192;
      }
      if (arguments.length === 2) {
        return this.randomGray(null, c, min);
      }
      if (c.str != null) {
        c.str = null;
      }
      r = this.randomInt2(min, max);
      for (i = _i = 0; _i <= 2; i = ++_i) {
        c[i] = r;
      }
      return c;
    },
    randomMapColor: function(c, set) {
      if (c == null) {
        c = [];
      }
      if (set == null) {
        set = [0, 63, 127, 191, 255];
      }
      return this.setColor(c, u.oneOf(set), u.oneOf(set), u.oneOf(set));
    },
    randomBrightColor: function(c) {
      if (c == null) {
        c = [];
      }
      return this.randomMapColor(c, [0, 127, 255]);
    },
    setColor: function(c, r, g, b, a) {
      if (a == null) {
        a = null;
      }
      if (c.str != null) {
        c.str = null;
      }
      c[0] = r;
      c[1] = g;
      c[2] = b;
      if (a != null) {
        c[3] = a;
      }
      return c;
    },
    scaleColor: function(max, s, c) {
      var i, val, _i, _len;

      if (c == null) {
        c = [];
      }
      if (c.str != null) {
        c.str = null;
      }
      for (i = _i = 0, _len = max.length; _i < _len; i = ++_i) {
        val = max[i];
        c[i] = this.clamp(Math.round(val * s), 0, 255);
      }
      return c;
    },
    colorStr: function(c) {
      var s;

      if ((s = c.str) != null) {
        return s;
      }
      return c.str = c.length === 3 ? "rgb(" + c + ")" : "rgba(" + c + ")";
    },
    colorsEqual: function(c1, c2) {
      return c1.toString() === c2.toString();
    },
    isLittleEndian: function() {
      var d32, d8;

      d8 = new Uint8ClampedArray(4);
      d32 = new Uint32Array(d8.buffer);
      d32[0] = 0x01020304;
      return d8[0] === 4;
    },
    degToRad: function(degrees) {
      return degrees * Math.PI / 180;
    },
    radToDeg: function(radians) {
      return radians * 180 / Math.PI;
    },
    subtractRads: function(rad1, rad2) {
      var PI, dr;

      dr = rad1 - rad2;
      PI = Math.PI;
      if (dr <= -PI) {
        dr += 2 * PI;
      }
      if (dr > PI) {
        dr -= 2 * PI;
      }
      return dr;
    },
    ownKeys: function(obj) {
      var key, value, _results;

      _results = [];
      for (key in obj) {
        if (!__hasProp.call(obj, key)) continue;
        value = obj[key];
        _results.push(key);
      }
      return _results;
    },
    ownVarKeys: function(obj) {
      var key, value, _results;

      _results = [];
      for (key in obj) {
        if (!__hasProp.call(obj, key)) continue;
        value = obj[key];
        if (!this.isFunction(value)) {
          _results.push(key);
        }
      }
      return _results;
    },
    any: function(array) {
      return array.length !== 0;
    },
    empty: function(array) {
      return array.length === 0;
    },
    clone: function(array) {
      return array.slice(0);
    },
    last: function(array) {
      if (this.empty(array)) {
        this.error("last: empty array");
      }
      return array[array.length - 1];
    },
    oneOf: function(array) {
      if (this.empty(array)) {
        this.error("oneOf: empty array");
      }
      return array[this.randomInt(array.length)];
    },
    nOf: function(array, n) {
      var o, r;

      if (n > array.length) {
        this.error("nOf: n > length");
      }
      r = [];
      while (r.length < n) {
        o = this.oneOf(array);
        if (__indexOf.call(r, o) < 0) {
          r.push(o);
        }
      }
      return r;
    },
    contains: function(array, item) {
      return -1 !== array.indexOf(item);
    },
    removeItem: function(array, item) {
      var i;

      if ((i = array.indexOf(item)) !== -1) {
        array.splice(i, 1);
      }
      if (i < 0) {
        this.error("removeItem: item not found");
      }
      return i;
    },
    shuffle: function(array) {
      return array.sort(function() {
        return 0.5 - Math.random();
      });
    },
    minOneOf: function(array, f, valueToo) {
      var a, o, r, r1, s, _i, _len;

      if (valueToo == null) {
        valueToo = false;
      }
      if (this.empty(array)) {
        this.error("minOneOf: empty array");
      }
      r = Infinity;
      o = null;
      if (this.isString(f)) {
        s = f;
        f = (function(o) {
          return o[s];
        });
      }
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        a = array[_i];
        if ((r1 = f(a)) < r) {
          r = r1;
          o = a;
        }
      }
      if (valueToo) {
        return [o, r];
      } else {
        return o;
      }
    },
    maxOneOf: function(array, f, valueToo) {
      var a, o, r, r1, s, _i, _len;

      if (valueToo == null) {
        valueToo = false;
      }
      if (this.empty(array)) {
        this.error("maxOneOf: empty array");
      }
      r = -Infinity;
      o = null;
      if (this.isString(f)) {
        s = f;
        f = (function(o) {
          return o[s];
        });
      }
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        a = array[_i];
        if ((r1 = f(a)) > r) {
          r = r1;
          o = a;
        }
      }
      if (valueToo) {
        return [o, r];
      } else {
        return o;
      }
    },
    histOf: function(array, bin, f) {
      var a, i, r, ri, s, val, _i, _j, _len, _len1;

      r = [];
      if (this.isString(f)) {
        s = f;
        f = (function(o) {
          return o[s];
        });
      }
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        a = array[_i];
        i = Math.floor(f(a) / bin);
        r[i] = (ri = r[i]) != null ? ri + 1 : 1;
      }
      for (i = _j = 0, _len1 = r.length; _j < _len1; i = ++_j) {
        val = r[i];
        if (val == null) {
          r[i] = 0;
        }
      }
      return r;
    },
    sortBy: function(array, prop) {
      return array.sort(function(a, b) {
        return a[prop] - b[prop];
      });
    },
    uniq: function(array) {
      var i, _i, _ref;

      for (i = _i = _ref = array.length - 1; _i >= 1; i = _i += -1) {
        if (array[i - 1] === array[i]) {
          array.splice(i, 1);
        }
      }
      return array;
    },
    flatten: function(matrix) {
      return matrix.reduce(function(a, b) {
        return a.concat(b);
      });
    },
    binarySearch: function(items, value, fcn) {
      var pivot, pivotVal, start, stop;

      if (fcn == null) {
        fcn = function(ex) {
          return ex;
        };
      }
      start = 0;
      stop = items.length - 1;
      pivot = Math.floor((start + stop) / 2);
      while ((pivotVal = fcn(items[pivot])) !== value && start < stop) {
        if (value < pivotVal) {
          stop = pivot - 1;
        }
        if (value > pivotVal) {
          start = pivot + 1;
        }
        pivot = Math.floor((stop + start) / 2);
      }
      if (fcn(items[pivot]) === value) {
        return pivot;
      } else {
        return -1;
      }
    },
    aMax: function(array) {
      return Math.max.apply(Math, array);
    },
    aMin: function(array) {
      return Math.min.apply(Math, array);
    },
    aPush: function(array, a) {
      return array.push.apply(array, a);
    },
    radsToward: function(x1, y1, x2, y2) {
      var PI, dx, dy;

      PI = Math.PI;
      dx = x2 - x1;
      dy = y2 - y1;
      if (dx === 0) {
        if (dy < 0) {
          return 3 * PI / 2;
        }
        if (dy > 0) {
          return PI / 2;
        }
        return 0;
      } else {
        return Math.atan(dy / dx) + (dx < 0 ? PI : 0);
      }
    },
    inCone: function(heading, cone, radius, x1, y1, x2, y2) {
      var angle12;

      if (radius < this.distance(x1, y1, x2, y2)) {
        return false;
      }
      angle12 = this.radsToward(x1, y1, x2, y2);
      return cone / 2 >= Math.abs(this.subtractRads(heading, angle12));
    },
    distance: function(x1, y1, x2, y2) {
      var dx, dy;

      dx = x1 - x2;
      dy = y1 - y2;
      return Math.sqrt(dx * dx + dy * dy);
    },
    sqDistance: function(x1, y1, x2, y2) {
      var dx, dy;

      dx = x1 - x2;
      dy = y1 - y2;
      return dx * dx + dy * dy;
    },
    torusDistance: function(x1, y1, x2, y2, w, h) {
      return Math.sqrt(this.torusSqDistance(x1, y1, x2, y2, w, h));
    },
    torusSqDistance: function(x1, y1, x2, y2, w, h) {
      var dx, dxMin, dy, dyMin;

      dx = Math.abs(x2 - x1);
      dy = Math.abs(y2 - y1);
      dxMin = Math.min(dx, w - dx);
      dyMin = Math.min(dy, h - dy);
      return dxMin * dxMin + dyMin * dyMin;
    },
    torusWraps: function(x1, y1, x2, y2, w, h) {
      var dx, dy;

      dx = Math.abs(x2 - x1);
      dy = Math.abs(y2 - y1);
      return dx > w - dx || dy > h - dy;
    },
    torus4Pts: function(x1, y1, x2, y2, w, h) {
      var x2r, y2r;

      x2r = x2 < x1 ? x2 + w : x2 - w;
      y2r = y2 < y1 ? y2 + h : y2 - h;
      return [[x2, y2], [x2r, y2], [x2, y2r], [x2r, y2r]];
    },
    torusPt: function(x1, y1, x2, y2, w, h) {
      var x, x2r, y, y2r;

      x2r = x2 < x1 ? x2 + w : x2 - w;
      y2r = y2 < y1 ? y2 + h : y2 - h;
      x = Math.abs(x2r - x1) < Math.abs(x2 - x1) ? x2r : x2;
      y = Math.abs(y2r - y1) < Math.abs(y2 - y1) ? y2r : y2;
      return [x, y];
    },
    torusRadsToward: function(x1, y1, x2, y2, w, h) {
      var _ref;

      _ref = this.torusPt(x1, y1, x2, y2, w, h), x2 = _ref[0], y2 = _ref[1];
      return this.radsToward(x1, y1, x2, y2);
    },
    inTorusCone: function(heading, cone, radius, x1, y1, x2, y2, w, h) {
      var p, _i, _len, _ref;

      _ref = this.torus4Pts(x1, y1, x2, y2, w, h);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        p = _ref[_i];
        if (this.inCone(heading, cone, radius, x1, y1, p[0], p[1])) {
          return true;
        }
      }
      return false;
    },
    createCanvas: function(width, height) {
      var can;

      can = document.createElement('canvas');
      can.width = width;
      can.height = height;
      return can;
    },
    createCtx: function(width, height, ctx) {
      var can;

      if (ctx == null) {
        ctx = "2d";
      }
      can = this.createCanvas(width, height);
      if (ctx === "2d") {
        return can.getContext("2d");
      } else {
        return can.getContext("webgl") || can.getContext("experimental-webgl");
      }
    },
    createLayer: function(div, width, height, z, ctx) {
      if (ctx == null) {
        ctx = "2d";
      }
      ctx = this.createCtx(width, height, ctx);
      ctx.canvas.setAttribute('style', "position:absolute;top:0;left:0;z-index:" + z);
      document.getElementById(div).appendChild(ctx.canvas);
      return ctx;
    },
    setIdentity: function(ctx) {
      ctx.save();
      return ctx.setTransform(1, 0, 0, 1, 0, 0);
    },
    clearCtx: function(ctx) {
      if (ctx.save != null) {
        this.setIdentity(ctx);
        ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
        return ctx.restore();
      } else {
        ctx.clearColor(0, 0, 0, 0);
        return ctx.clear(ctx.COLOR_BUFFER_BIT | ctx.DEPTH_BUFFER_BIT);
      }
    },
    fillCtx: function(ctx, color) {
      if (ctx.fillStyle != null) {
        this.setIdentity(ctx);
        ctx.fillStyle = this.colorStr(color);
        ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
        return ctx.restore();
      } else {
        ctx.clearColor.apply(ctx, __slice.call(color).concat([1]));
        return ctx.clear(ctx.COLOR_BUFFER_BIT | ctx.DEPTH_BUFFER_BIT);
      }
    },
    ctxDrawText: function(ctx, string, xy, color) {
      if (color == null) {
        color = [0, 0, 0];
      }
      ctx.fillStyle = this.colorStr(color);
      return ctx.fillText(string, xy[0], xy[1]);
    },
    ctxTextParams: function(ctx, font, align, baseline) {
      if (align == null) {
        align = "center";
      }
      if (baseline == null) {
        baseline = "middle";
      }
      ctx.font = font;
      ctx.textAlign = align;
      return ctx.textBaseline = baseline;
    },
    ctxLabelParams: function(ctx, color, xy) {
      ctx.labelColor = color;
      return ctx.labelXY = xy;
    },
    importImage: function(imageSrc, f) {
      var img;

      if (f == null) {
        f = null;
      }
      img = new Image();
      img.onload = function() {
        if (f != null) {
          return f(img);
        }
      };
      img.src = imageSrc;
      return img;
    },
    imageToCtx: function(image) {
      var ctx;

      ctx = this.createCtx(image.width, image.height);
      ctx.drawImage(image, 0, 0);
      return ctx;
    },
    ctxToImage: function(ctx, f) {
      var img;

      if (f == null) {
        f = null;
      }
      img = new Image();
      img.onload = function() {
        if (f != null) {
          return f(img);
        }
      };
      return img.src = ctx.canvas.toDataURL("image/png");
    },
    ctxToImageData: function(ctx) {
      return ctx.getImageData(0, 0, ctx.canvas.width, ctx.canvas.height);
    },
    canvasToImage: function(canvas) {
      return ctxToImage(canvas.getContext("2d"));
    },
    canvasToImageData: function(canvas) {
      return ctxToImageData(canvas.getContext("2d"));
    },
    imageToCanvas: function(image) {
      return imageToCtx(image).canvas;
    },
    drawCenteredImage: function(ctx, img, rad, x, y, dx, dy) {
      ctx.translate(x, y);
      ctx.rotate(rad);
      return ctx.drawImage(img, -dx / 2, -dy / 2);
    },
    copyCtx: function(ctx0) {
      var ctx;

      ctx = this.createCtx(ctx0.canvas.width, ctx0.canvas.height);
      ctx.drawImage(ctx0.canvas, 0, 0);
      return ctx;
    },
    resizeCtx: function(ctx, width, height, scale) {
      var copy;

      if (scale == null) {
        scale = false;
      }
      copy = this.copyCtx(ctx);
      ctx.canvas.width = width;
      ctx.canvas.height = height;
      return ctx.drawImage(copy.canvas, 0, 0);
    }
  };

  ABM.shapes = ABM.util.s = (function() {
    var ccirc, cimg, circ, csq, fillSlot, poly, spriteSheets;

    poly = function(c, a) {
      var i, p, _i, _len;

      for (i = _i = 0, _len = a.length; _i < _len; i = ++_i) {
        p = a[i];
        if (i === 0) {
          c.moveTo(p[0], p[1]);
        } else {
          c.lineTo(p[0], p[1]);
        }
      }
      return null;
    };
    circ = function(c, x, y, s) {
      return c.arc(x, y, s / 2, 0, 2 * Math.PI);
    };
    ccirc = function(c, x, y, s) {
      return c.arc(x, y, s / 2, 0, 2 * Math.PI, true);
    };
    cimg = function(c, x, y, s, img) {
      c.scale(1, -1);
      c.drawImage(img, x - s / 2, y - s / 2, s, s);
      return c.scale(1, -1);
    };
    csq = function(c, x, y, s) {
      return c.fillRect(x - s / 2, y - s / 2, s, s);
    };
    fillSlot = function(slot, img) {
      slot.ctx.save();
      slot.ctx.scale(1, -1);
      slot.ctx.drawImage(img, slot.x, -(slot.y + slot.bits), slot.bits, slot.bits);
      return slot.ctx.restore();
    };
    spriteSheets = [];
    return {
      "default": {
        rotate: true,
        draw: function(c) {
          return poly(c, [[.5, 0], [-.5, -.5], [-.25, 0], [-.5, .5]]);
        }
      },
      triangle: {
        rotate: true,
        draw: function(c) {
          return poly(c, [[.5, 0], [-.5, -.4], [-.5, .4]]);
        }
      },
      arrow: {
        rotate: true,
        draw: function(c) {
          return poly(c, [[.5, 0], [0, .5], [0, .2], [-.5, .2], [-.5, -.2], [0, -.2], [0, -.5]]);
        }
      },
      bug: {
        rotate: true,
        draw: function(c) {
          c.strokeStyle = c.fillStyle;
          c.lineWidth = .05;
          poly(c, [[.4, .225], [.2, 0], [.4, -.225]]);
          c.stroke();
          c.beginPath();
          circ(c, .12, 0, .26);
          circ(c, -.05, 0, .26);
          return circ(c, -.27, 0, .4);
        }
      },
      pyramid: {
        rotate: false,
        draw: function(c) {
          return poly(c, [[0, .5], [-.433, -.25], [.433, -.25]]);
        }
      },
      circle: {
        shortcut: function(c, x, y, s) {
          c.beginPath();
          circ(c, x, y, s);
          c.closePath();
          return c.fill();
        },
        rotate: false,
        draw: function(c) {
          return circ(c, 0, 0, 1);
        }
      },
      square: {
        shortcut: function(c, x, y, s) {
          return csq(c, x, y, s);
        },
        rotate: false,
        draw: function(c) {
          return csq(c, 0, 0, 1);
        }
      },
      pentagon: {
        rotate: false,
        draw: function(c) {
          return poly(c, [[0, .45], [-.45, .1], [-.3, -.45], [.3, -.45], [.45, .1]]);
        }
      },
      ring: {
        rotate: false,
        draw: function(c) {
          circ(c, 0, 0, 1);
          c.closePath();
          return ccirc(c, 0, 0, .6);
        }
      },
      cup: {
        shortcut: function(c, x, y, s) {
          return cimg(c, x, y, s, this.img);
        },
        rotate: false,
        img: u.importImage("http://goo.gl/LTIyR"),
        draw: function(c) {
          return cimg(c, .5, .5, 1, this.img);
        }
      },
      person: {
        rotate: false,
        draw: function(c) {
          poly(c, [[.15, .2], [.3, 0], [.125, -.1], [.125, .05], [.1, -.15], [.25, -.5], [.05, -.5], [0, -.25], [-.05, -.5], [-.25, -.5], [-.1, -.15], [-.125, .05], [-.125, -.1], [-.3, 0], [-.15, .2]]);
          c.closePath();
          return circ(c, 0, .35, .30);
        }
      },
      names: function() {
        var name, val, _results;

        _results = [];
        for (name in this) {
          if (!__hasProp.call(this, name)) continue;
          val = this[name];
          if ((val.rotate != null) && (val.draw != null)) {
            _results.push(name);
          }
        }
        return _results;
      },
      add: function(name, rotate, draw, shortcut) {
        var s;

        if (shortcut == null) {
          shortcut = null;
        }
        s = this[name] = u.isFunction(draw) ? {
          rotate: rotate,
          draw: draw
        } : {
          rotate: rotate,
          img: draw,
          draw: function(c) {
            return cimg(c, .5, .5, 1, this.img);
          }
        };
        if ((s.img != null) && !s.rotate) {
          s.shortcut = function(c, x, y, s) {
            return cimg(c, x, y, s, this.img);
          };
        }
        if (shortcut != null) {
          return s.shortcut = shortcut;
        }
      },
      poly: poly,
      circ: circ,
      ccirc: ccirc,
      cimg: cimg,
      csq: csq,
      spriteSheets: spriteSheets,
      draw: function(ctx, shape, x, y, size, rad, color) {
        if (shape.shortcut != null) {
          if (shape.img == null) {
            ctx.fillStyle = u.colorStr(color);
          }
          shape.shortcut(ctx, x, y, size);
        } else {
          ctx.save();
          ctx.translate(x, y);
          if (size !== 1) {
            ctx.scale(size, size);
          }
          if (rad !== 0) {
            ctx.rotate(rad);
          }
          if (shape.img != null) {
            shape.draw(ctx);
          } else {
            ctx.fillStyle = u.colorStr(color);
            ctx.beginPath();
            shape.draw(ctx);
            ctx.closePath();
            ctx.fill();
          }
          ctx.restore();
        }
        return shape;
      },
      drawSprite: function(ctx, s, x, y, size, rad) {
        if (rad === 0) {
          ctx.drawImage(s.ctx.canvas, s.x, s.y, s.bits, s.bits, x - size / 2, y - size / 2, size, size);
        } else {
          ctx.save();
          ctx.translate(x, y);
          ctx.rotate(rad);
          ctx.drawImage(s.ctx.canvas, s.x, s.y, s.bits, s.bits, -size / 2, -size / 2, size, size);
          ctx.restore();
        }
        return s;
      },
      shapeToSprite: function(name, color, size) {
        var bits, ctx, foundSlot, img, index, shape, slot, x, y;

        bits = Math.ceil(size * ABM.patches.size);
        shape = this[name];
        index = shape.img != null ? name : "" + name + "-" + (u.colorStr(color));
        ctx = spriteSheets[bits];
        if (ctx == null) {
          spriteSheets[bits] = ctx = u.createCtx(bits * 10, bits);
          ctx.nextX = 0;
          ctx.nextY = 0;
          ctx.index = {};
        }
        if ((foundSlot = ctx.index[index]) != null) {
          return foundSlot;
        }
        if (bits * ctx.nextX === ctx.canvas.width) {
          u.resizeCtx(ctx, ctx.canvas.width, ctx.canvas.height + bits);
          ctx.nextX = 0;
          ctx.nextY++;
        }
        x = bits * ctx.nextX;
        y = bits * ctx.nextY;
        slot = {
          ctx: ctx,
          x: x,
          y: y,
          size: size,
          bits: bits,
          name: name,
          color: color,
          index: index
        };
        ctx.index[index] = slot;
        if ((img = shape.img) != null) {
          if (img.height !== 0) {
            fillSlot(slot, img);
          } else {
            img.onload = function() {
              return fillSlot(slot, img);
            };
          }
        } else {
          ctx.save();
          ctx.scale(bits, bits);
          ctx.translate(ctx.nextX + .5, ctx.nextY + .5);
          ctx.fillStyle = u.colorStr(color);
          ctx.beginPath();
          shape.draw(ctx);
          ctx.closePath();
          ctx.fill();
          ctx.restore();
        }
        ctx.nextX++;
        return slot;
      }
    };
  })();

  ABM.AgentSet = (function(_super) {
    __extends(AgentSet, _super);

    AgentSet.asSet = function(a, setType) {
      var _ref;

      if (setType == null) {
        setType = ABM.AgentSet;
      }
      a.__proto__ = (_ref = setType.prototype) != null ? _ref : setType.constructor.prototype;
      return a;
    };

    function AgentSet(agentClass, name, mainSet) {
      this.agentClass = agentClass;
      this.name = name;
      this.mainSet = mainSet != null ? mainSet : null;
      AgentSet.__super__.constructor.call(this);
      this.agentClass.prototype.breed = this;
      this.ownVariables = [];
      if (this.mainSet == null) {
        this.ID = 0;
      }
    }

    AgentSet.prototype.create = function() {};

    AgentSet.prototype.add = function(o) {
      if (this.mainSet != null) {
        this.mainSet.add(o);
      } else {
        o.id = this.ID++;
      }
      this.push(o);
      return o;
    };

    AgentSet.prototype.remove = function(o) {
      var i;

      if (this.mainSet != null) {
        this.mainSet.remove(o);
      }
      if (this.length === 0) {
        u.error("remove: empty arraySet");
      }
      if (o === this.last()) {
        this[--this.length] = null;
      } else {
        if ((i = this.indexOfID(o.id)) !== -1) {
          this.splice(i, 1);
        }
        if (i === -1) {
          u.error("remove: indexOfID not in list");
        }
      }
      return this;
    };

    AgentSet.prototype.setDefault = function(name, value) {
      if (typeof name !== "string") {
        u.error("setDefault: name is not a string");
      }
      return this.agentClass.prototype[name] = value;
    };

    AgentSet.prototype.own = function() {
      var i, name, nameValueList, _i, _len, _results;

      nameValueList = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (nameValueList.length % 2 !== 0) {
        u.error("own: odd number of arguments");
      }
      _results = [];
      for (i = _i = 0, _len = nameValueList.length; _i < _len; i = _i += 2) {
        name = nameValueList[i];
        this.setDefault(name, nameValueList[i + 1]);
        _results.push(this.ownVariables.push(name));
      }
      return _results;
    };

    AgentSet.prototype.uniq = function() {
      return u.uniq(this);
    };

    AgentSet.prototype.withID = function(id) {
      var i;

      if ((i = this.indexOfID(id)) !== -1) {
        return this[i];
      } else {
        return null;
      }
    };

    AgentSet.prototype.indexOfID = function(id, sorted) {
      if (sorted == null) {
        sorted = true;
      }
      if (!sorted) {
        this.sortById();
      }
      if (id === this.last().id) {
        return this.length - 1;
      }
      return u.binarySearch(this, id, function(o) {
        return o.id;
      });
    };

    AgentSet.prototype.asSet = function(a) {
      return ABM.AgentSet.asSet(a);
    };

    AgentSet.prototype.asOrderedSet = function(a) {
      return this.asSet(a).sortById();
    };

    AgentSet.prototype.toString = function() {
      var a;

      return "[" + ((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          a = this[_i];
          _results.push(a.toString());
        }
        return _results;
      }).call(this)).join(", ") + "]";
    };

    AgentSet.prototype.getProp = function(prop) {
      var o, _i, _len, _results;

      _results = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        o = this[_i];
        _results.push(o[prop]);
      }
      return _results;
    };

    AgentSet.prototype.getProps = function(props) {
      var o, p, _i, _len, _results;

      if (u.isString(props)) {
        props = props.split(" ");
      }
      _results = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        o = this[_i];
        _results.push((function() {
          var _j, _len1, _results1;

          _results1 = [];
          for (_j = 0, _len1 = props.length; _j < _len1; _j++) {
            p = props[_j];
            _results1.push(o[p]);
          }
          return _results1;
        })());
      }
      return _results;
    };

    AgentSet.prototype.getPropWith = function(prop, value) {
      var o;

      return this.asSet((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          o = this[_i];
          if (o[prop] === value) {
            _results.push(o);
          }
        }
        return _results;
      }).call(this));
    };

    AgentSet.prototype.setProp = function(prop, value) {
      var o, _i, _len;

      for (_i = 0, _len = this.length; _i < _len; _i++) {
        o = this[_i];
        o[prop] = value;
      }
      return this;
    };

    AgentSet.prototype.maxProp = function(prop) {
      return Math.max.apply(Math, this.getProp(prop));
    };

    AgentSet.prototype.minProp = function(prop) {
      return Math.min.apply(Math, this.getProp(prop));
    };

    AgentSet.prototype.shuffle = function() {
      return u.shuffle(this);
    };

    AgentSet.prototype.sortById = function() {
      return u.sortBy(this, "id");
    };

    AgentSet.prototype.clone = function() {
      return this.asSet(u.clone(this));
    };

    AgentSet.prototype.last = function() {
      return u.last(this);
    };

    AgentSet.prototype.any = function() {
      return u.any(this);
    };

    AgentSet.prototype.other = function(a) {
      var o;

      return this.asSet((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          o = this[_i];
          if (o !== a) {
            _results.push(o);
          }
        }
        return _results;
      }).call(this));
    };

    AgentSet.prototype.oneOf = function() {
      return u.oneOf(this);
    };

    AgentSet.prototype.nOf = function(n) {
      return this.asSet(u.nOf(this, n));
    };

    AgentSet.prototype.minOneOf = function(f, valueToo) {
      if (valueToo == null) {
        valueToo = false;
      }
      return u.minOneOf(this, f, valueToo);
    };

    AgentSet.prototype.maxOneOf = function(f, valueToo) {
      if (valueToo == null) {
        valueToo = false;
      }
      return u.maxOneOf(this, f, valueToo);
    };

    AgentSet.prototype.draw = function(ctx) {
      var o, _i, _len;

      u.clearCtx(ctx);
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        o = this[_i];
        if (!o.hidden) {
          o.draw(ctx);
        }
      }
      return null;
    };

    AgentSet.prototype.inRadius = function(o, d, meToo) {
      var a, d2, h, w, x, y;

      if (meToo == null) {
        meToo = false;
      }
      d2 = d * d;
      x = o.x;
      y = o.y;
      if (ABM.patches.isTorus) {
        w = ABM.patches.numX;
        h = ABM.patches.numY;
        return this.asSet((function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = this.length; _i < _len; _i++) {
            a = this[_i];
            if (u.torusSqDistance(x, y, a.x, a.y, w, h) <= d2 && (meToo || a !== o)) {
              _results.push(a);
            }
          }
          return _results;
        }).call(this));
      } else {
        return this.asSet((function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = this.length; _i < _len; _i++) {
            a = this[_i];
            if (u.sqDistance(x, y, a.x, a.y) <= d2 && (meToo || a !== o)) {
              _results.push(a);
            }
          }
          return _results;
        }).call(this));
      }
    };

    AgentSet.prototype.inCone = function(o, heading, cone, radius, meToo) {
      var a, h, rSet, w, x, y;

      if (meToo == null) {
        meToo = false;
      }
      rSet = this.inRadius(o, radius, meToo);
      x = o.x;
      y = o.y;
      if (ABM.patches.isTorus) {
        w = ABM.patches.numX;
        h = ABM.patches.numY;
        return this.asSet((function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = rSet.length; _i < _len; _i++) {
            a = rSet[_i];
            if ((a === o && meToo) || u.inTorusCone(heading, cone, radius, x, y, a.x, a.y, w, h)) {
              _results.push(a);
            }
          }
          return _results;
        })());
      } else {
        return this.asSet((function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = rSet.length; _i < _len; _i++) {
            a = rSet[_i];
            if ((a === o && meToo) || u.inCone(heading, cone, radius, x, y, a.x, a.y)) {
              _results.push(a);
            }
          }
          return _results;
        })());
      }
    };

    AgentSet.prototype.ask = function(f) {
      var o, _i, _len;

      if (u.isString(f)) {
        eval("f=function(o){return " + f + ";}");
      }
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        o = this[_i];
        f(o);
      }
      return this;
    };

    AgentSet.prototype["with"] = function(f) {
      var o;

      if (u.isString(f)) {
        eval("f=function(o){return " + f + ";}");
      }
      return this.asSet((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          o = this[_i];
          if (f(o)) {
            _results.push(o);
          }
        }
        return _results;
      }).call(this));
    };

    return AgentSet;

  })(Array);

  ABM.Patch = (function() {
    Patch.prototype.n = null;

    Patch.prototype.n4 = null;

    Patch.prototype.color = [0, 0, 0];

    Patch.prototype.hidden = false;

    Patch.prototype.label = null;

    Patch.prototype.breed = null;

    function Patch(x, y) {
      this.x = x;
      this.y = y;
    }

    Patch.prototype.toString = function() {
      return "{id:" + this.id + " xy:" + (u.aToFixed([this.x, this.y])) + " c:" + this.color + "}";
    };

    Patch.prototype.scaleColor = function(c, s) {
      if (!this.hasOwnProperty("color")) {
        this.color = u.clone(this.color);
      }
      return u.scaleColor(c, s, this.color);
    };

    Patch.prototype.draw = function(ctx) {
      var x, y, _ref;

      ctx.fillStyle = u.colorStr(this.color);
      ctx.fillRect(this.x - .5, this.y - .5, 1, 1);
      if (this.label != null) {
        _ref = ctx.labelXY, x = _ref[0], y = _ref[1];
        ctx.save();
        ctx.translate(this.x, this.y);
        ctx.scale(1 / ABM.patches.size, -1 / ABM.patches.size);
        u.ctxDrawText(ctx, this.label, [x, y], ctx.labelColor);
        return ctx.restore();
      }
    };

    Patch.prototype.agentsHere = function() {
      var a, _ref;

      return (_ref = this.agents) != null ? _ref : (function() {
        var _i, _len, _ref1, _results;

        _ref1 = ABM.agents;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          a = _ref1[_i];
          if (a.p === this) {
            _results.push(a);
          }
        }
        return _results;
      }).call(this);
    };

    Patch.prototype.isOnEdge = function() {
      return this.x === ABM.patches.minX || this.x === ABM.patches.maxX || this.y === ABM.patches.minY || this.y === ABM.patches.maxY;
    };

    Patch.prototype.sprout = function(num, breed, init) {
      var _this = this;

      if (num == null) {
        num = 1;
      }
      if (breed == null) {
        breed = ABM.agents;
      }
      if (init == null) {
        init = function() {};
      }
      return breed.create(num, function(a) {
        a.setXY(_this.x, _this.y);
        init(a);
        return a;
      });
    };

    return Patch;

  })();

  ABM.Patches = (function(_super) {
    __extends(Patches, _super);

    function Patches() {
      var k, v, x, y, _i, _j, _ref, _ref1, _ref2, _ref3, _ref4;

      Patches.__super__.constructor.apply(this, arguments);
      _ref = ABM.world;
      for (k in _ref) {
        if (!__hasProp.call(_ref, k)) continue;
        v = _ref[k];
        this[k] = v;
      }
      ABM.world.numX = this.numX = this.maxX - this.minX + 1;
      ABM.world.numY = this.numY = this.maxY - this.minY + 1;
      for (y = _i = _ref1 = this.minY, _ref2 = this.maxY; _i <= _ref2; y = _i += 1) {
        for (x = _j = _ref3 = this.minX, _ref4 = this.maxX; _j <= _ref4; x = _j += 1) {
          this.add(new ABM.Patch(x, y));
        }
      }
      if (this.hasNeighbors) {
        this.setNeighbors();
      }
      this.setPixels();
      this.drawWithPixels = this.size === 1;
    }

    Patches.prototype.setDefaultColor = function(color) {
      return ABM.Patch.prototype.color = color;
    };

    Patches.prototype.cacheAgentsHere = function() {
      var p, _i, _len;

      for (_i = 0, _len = this.length; _i < _len; _i++) {
        p = this[_i];
        p.agents = [];
      }
      return null;
    };

    Patches.prototype.usePixels = function(usePix) {
      var ctx;

      if (usePix == null) {
        usePix = true;
      }
      ctx = ABM.contexts.patches;
      ctx.imageSmoothingEnabled = !usePix;
      ctx.mozImageSmoothingEnabled = !usePix;
      ctx.webkitImageSmoothingEnabled = !usePix;
      u.setIdentity(ctx);
      return this.drawWithPixels = usePix;
    };

    Patches.prototype.cacheRect = function(radius, meToo) {
      var p, _i, _len, _results;

      if (meToo == null) {
        meToo = false;
      }
      _results = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        p = this[_i];
        p.pRect = this.patchRect(p, radius, radius, meToo);
        p.pRect.radius = radius;
        _results.push(p.pRect.meToo = meToo);
      }
      return _results;
    };

    Patches.prototype.setNeighbors = function() {
      var n, p, _i, _len, _results;

      _results = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        p = this[_i];
        p.n = this.patchRect(p, 1, 1);
        _results.push(p.n4 = this.asSet((function() {
          var _j, _len1, _ref, _results1;

          _ref = p.n;
          _results1 = [];
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            n = _ref[_j];
            if (n.x === p.x || n.y === p.y) {
              _results1.push(n);
            }
          }
          return _results1;
        })()));
      }
      return _results;
    };

    Patches.prototype.setPixels = function() {
      var can;

      if (this.size === 1) {
        this.pixelsCtx = ABM.contexts.patches;
      } else {
        can = document.createElement('canvas');
        can.width = this.numX;
        can.height = this.numY;
        this.pixelsCtx = can.getContext("2d");
      }
      this.pixelsImageData = this.pixelsCtx.getImageData(0, 0, this.numX, this.numY);
      this.pixelsData = this.pixelsImageData.data;
      if (this.pixelsData instanceof Uint8Array) {
        this.pixelsData32 = new Uint32Array(this.pixelsData.buffer);
        return this.pixelsAreLittleEndian = u.isLittleEndian();
      }
    };

    Patches.prototype.draw = function(ctx) {
      if (this.drawWithPixels) {
        return this.drawScaledPixels(ctx);
      } else {
        return Patches.__super__.draw.call(this, ctx);
      }
    };

    Patches.prototype.patchXY = function(x, y) {
      return this[x - this.minX + this.numX * (y - this.minY)];
    };

    Patches.prototype.clamp = function(x, y) {
      return [u.clamp(x, this.minX - .5, this.maxX + .5), u.clamp(y, this.minY - .5, this.maxY + .5)];
    };

    Patches.prototype.wrap = function(x, y) {
      return [u.wrap(x, this.minX - .5, this.maxX + .5), u.wrap(y, this.minY - .5, this.maxY + .5)];
    };

    Patches.prototype.coord = function(x, y) {
      if (this.isTorus) {
        return this.wrap(x, y);
      } else {
        return this.clamp(x, y);
      }
    };

    Patches.prototype.patch = function(x, y) {
      var _ref;

      _ref = this.coord(x, y), x = _ref[0], y = _ref[1];
      x = u.clamp(Math.round(x), this.minX, this.maxX);
      y = u.clamp(Math.round(y), this.minY, this.maxY);
      return this.patchXY(x, y);
    };

    Patches.prototype.randomPt = function() {
      return [u.randomFloat2(this.minX - .5, this.maxX + .5), u.randomFloat2(this.minY - .5, this.maxY + .5)];
    };

    Patches.prototype.bitWidth = function() {
      return this.numX * this.size;
    };

    Patches.prototype.bitHeight = function() {
      return this.numY * this.size;
    };

    Patches.prototype.patches2Bits = function(p) {
      return p * this.size;
    };

    Patches.prototype.bits2Patches = function(b) {
      return b / this.size;
    };

    Patches.prototype.patchRect = function(p, dx, dy, meToo) {
      var pnext, rect, x, y, _i, _j, _ref, _ref1, _ref2, _ref3;

      if (meToo == null) {
        meToo = false;
      }
      if ((p.pRect != null) && p.pRect.radius === dx && p.pRect.radius === dy) {
        return p.pRect;
      }
      rect = [];
      for (y = _i = _ref = p.y - dy, _ref1 = p.y + dy; _i <= _ref1; y = _i += 1) {
        for (x = _j = _ref2 = p.x - dx, _ref3 = p.x + dx; _j <= _ref3; x = _j += 1) {
          if (this.isTorus || ((this.minX <= x && x <= this.maxX) && (this.minY <= y && y <= this.maxY))) {
            if (this.isTorus) {
              if (x < this.minX) {
                x += this.numX;
              }
              if (x > this.maxX) {
                x -= this.numX;
              }
              if (y < this.minY) {
                y += this.numY;
              }
              if (y > this.maxY) {
                y -= this.numY;
              }
            }
            pnext = this.patchXY(x, y);
            if (pnext == null) {
              u.error("patchRect: x,y out of bounds, see console.log");
              console.log("x " + x + " y " + y + " p.x " + p.x + " p.y " + p.y + " dx " + dx + " dy " + dy);
            }
            if (meToo || p !== pnext) {
              rect.push(pnext);
            }
          }
        }
      }
      return this.asSet(rect);
    };

    Patches.prototype.importDrawing = function(imageSrc) {
      return u.importImage(imageSrc, function(img) {
        var ctx;

        ctx = ABM.drawing;
        u.setIdentity(ctx);
        ctx.drawImage(img, 0, 0, ctx.canvas.width, ctx.canvas.height);
        return ctx.restore();
      });
    };

    Patches.prototype.pixelIndex = function(p) {
      return ((p.x - this.minX) + (this.maxY - p.y) * this.numX) * 4;
    };

    Patches.prototype.importColors = function(imageSrc) {
      var _this = this;

      return u.importImage(imageSrc, function(img) {
        var data, i, j, p, _i, _len;

        if (img.width !== _this.numX || img.height !== _this.numY) {
          _this.pixelsCtx.drawImage(img, 0, 0, _this.numX, _this.numY);
        } else {
          _this.pixelsCtx.drawImage(img, 0, 0);
        }
        data = _this.pixelsCtx.getImageData(0, 0, _this.numX, _this.numY).data;
        for (_i = 0, _len = _this.length; _i < _len; _i++) {
          p = _this[_i];
          i = _this.pixelIndex(p);
          p.color = (function() {
            var _j, _results;

            _results = [];
            for (j = _j = 0; _j <= 2; j = ++_j) {
              _results.push(data[i + j]);
            }
            return _results;
          })();
        }
        return null;
      });
    };

    Patches.prototype.drawScaledPixels = function(ctx) {
      if (this.pixelsData32 != null) {
        return this.drawScaledPixels32(ctx);
      } else {
        return this.drawScaledPixels8(ctx);
      }
    };

    Patches.prototype.drawScaledPixels8 = function(ctx) {
      var c, data, i, j, maxY, minX, numX, p, _i, _j, _len;

      data = this.pixelsData;
      minX = this.minX;
      numX = this.numX;
      maxY = this.maxY;
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        p = this[_i];
        i = ((p.x - minX) + (maxY - p.y) * numX) * 4;
        c = p.color;
        for (j = _j = 0; _j <= 2; j = ++_j) {
          data[i + j] = c[j];
        }
        data[i + 3] = c.length === 4 ? c[3] : 255;
      }
      this.pixelsCtx.putImageData(this.pixelsImageData, 0, 0);
      if (this.size === 1) {
        return;
      }
      return ctx.drawImage(this.pixelsCtx.canvas, 0, 0, ctx.canvas.width, ctx.canvas.height);
    };

    Patches.prototype.drawScaledPixels32 = function(ctx) {
      var a, c, data, i, maxY, minX, numX, p, _i, _len;

      data = this.pixelsData32;
      minX = this.minX;
      numX = this.numX;
      maxY = this.maxY;
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        p = this[_i];
        i = (p.x - minX) + (maxY - p.y) * numX;
        c = p.color;
        a = c.length === 4 ? c[3] : 255;
        if (this.pixelsAreLittleEndian) {
          data[i] = (a << 24) | (c[2] << 16) | (c[1] << 8) | c[0];
        } else {
          data[i] = (c[0] << 24) | (c[1] << 16) | (c[2] << 8) | a;
        }
      }
      this.pixelsCtx.putImageData(this.pixelsImageData, 0, 0);
      if (this.size === 1) {
        return;
      }
      return ctx.drawImage(this.pixelsCtx.canvas, 0, 0, ctx.canvas.width, ctx.canvas.height);
    };

    Patches.prototype.diffuse = function(v, rate, c) {
      var dv, dv8, n, nn, p, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref;

      if (c == null) {
        c = null;
      }
      if (this[0]._diffuseNext == null) {
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          p = this[_i];
          p._diffuseNext = 0;
        }
      }
      for (_j = 0, _len1 = this.length; _j < _len1; _j++) {
        p = this[_j];
        dv = p[v] * rate;
        dv8 = dv / 8;
        nn = p.n.length;
        p._diffuseNext += p[v] - dv + (8 - nn) * dv8;
        _ref = p.n;
        for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
          n = _ref[_k];
          n._diffuseNext += dv8;
        }
      }
      for (_l = 0, _len3 = this.length; _l < _len3; _l++) {
        p = this[_l];
        p[v] = p._diffuseNext;
        p._diffuseNext = 0;
        if (c) {
          p.scaleColor(c, p[v]);
        }
      }
      return null;
    };

    return Patches;

  })(ABM.AgentSet);

  ABM.Agent = (function() {
    Agent.prototype.color = null;

    Agent.prototype.shape = "default";

    Agent.prototype.breed = null;

    Agent.prototype.hidden = false;

    Agent.prototype.size = 1;

    Agent.prototype.penDown = false;

    Agent.prototype.penSize = 1;

    Agent.prototype.heading = null;

    Agent.prototype.sprite = null;

    Agent.prototype.cacheLinks = false;

    function Agent() {
      this.x = this.y = 0;
      if (this.color == null) {
        this.color = u.randomColor();
      }
      if (this.heading == null) {
        this.heading = u.randomFloat(Math.PI * 2);
      }
      this.p = ABM.patches.patch(this.x, this.y);
      if (this.p.agents != null) {
        this.p.agents.push(this);
      }
      if (this.cacheLinks) {
        this.links = [];
      }
    }

    Agent.prototype.changeBreed = function(newBreed) {
      var _this = this;

      if (this.id == null) {
        u.error("changeBreed: not in agentSet");
      }
      if (this.hasOwnProperty("breed")) {
        u.error("changeBreed: breed illegally set");
      }
      if (this.breed === newBreed) {
        u.error("changeBreed: breed==newBreed");
      }
      this.die();
      return newBreed.create(1, function(a) {
        return a.setXY(_this.x, _this.y);
      });
    };

    Agent.prototype.scaleColor = function(c, s) {
      if (!this.hasOwnProperty("color")) {
        this.color = u.clone(this.color);
      }
      return u.scaleColor(c, s, this.color);
    };

    Agent.prototype.toString = function() {
      return "{id:" + this.id + " xy:" + (u.aToFixed([this.x, this.y])) + " c:" + this.color + " h: " + (this.heading.toFixed(2)) + "}";
    };

    Agent.prototype.setXY = function(x, y) {
      var drawing, p, x0, y0, _ref, _ref1;

      if (this.penDown) {
        _ref = [this.x, this.y], x0 = _ref[0], y0 = _ref[1];
      }
      _ref1 = ABM.patches.coord(x, y), this.x = _ref1[0], this.y = _ref1[1];
      p = this.p;
      this.p = ABM.patches.patch(this.x, this.y);
      if ((p.agents != null) && p !== this.p) {
        u.removeItem(p.agents, this);
        this.p.agents.push(this);
      }
      if (this.penDown) {
        drawing = ABM.drawing;
        drawing.strokeStyle = u.colorStr(this.color);
        drawing.lineWidth = ABM.patches.bits2Patches(this.penSize);
        drawing.beginPath();
        drawing.moveTo(x0, y0);
        drawing.lineTo(x, y);
        return drawing.stroke();
      }
    };

    Agent.prototype.moveTo = function(a) {
      return this.setXY(a.x, a.y);
    };

    Agent.prototype.forward = function(d) {
      return this.setXY(this.x + d * Math.cos(this.heading), this.y + d * Math.sin(this.heading));
    };

    Agent.prototype.rotate = function(rad) {
      return this.heading = u.wrap(this.heading + rad, 0, Math.PI * 2);
    };

    Agent.prototype.draw = function(ctx) {
      var rad, shape;

      shape = ABM.shapes[this.shape];
      rad = shape.rotate ? this.heading : 0;
      if ((this.sprite != null) || this.breed.useSprites) {
        if (this.sprite == null) {
          this.setSprite();
        }
        return ABM.shapes.drawSprite(ctx, this.sprite, this.x, this.y, this.size, rad);
      } else {
        return ABM.shapes.draw(ctx, shape, this.x, this.y, this.size, rad, this.color);
      }
    };

    Agent.prototype.setSprite = function(sprite) {
      var s;

      if (sprite == null) {
        sprite = null;
      }
      if ((s = sprite) != null) {
        this.sprite = s;
        this.color = s.color;
        this.shape = s.shape;
        return this.size = s.size;
      } else {
        if (this.color == null) {
          this.color = u.randomColor;
        }
        return this.sprite = ABM.shapes.shapeToSprite(this.shape, this.color, this.size);
      }
    };

    Agent.prototype.stamp = function() {
      return this.draw(ABM.drawing);
    };

    Agent.prototype.distanceXY = function(x, y) {
      if (ABM.patches.isTorus) {
        return u.torusDistance(this.x, this.y, x, y, ABM.patches.numX, ABM.patches.numY);
      } else {
        return u.distance(this.x, this.y, x, y);
      }
    };

    Agent.prototype.distance = function(o) {
      return this.distanceXY(o.x, o.y);
    };

    Agent.prototype.torusPtXY = function(x, y) {
      return u.torusPt(this.x, this.y, x, y, ABM.patches.numX, ABM.patches.numY);
    };

    Agent.prototype.torusPt = function(o) {
      return this.torusPtXY(o.x, o.y);
    };

    Agent.prototype.face = function(o) {
      return this.heading = this.towards(o);
    };

    Agent.prototype.towardsXY = function(x, y) {
      if (ABM.patches.isTorus) {
        return u.torusRadsToward(this.x, this.y, x, y, ABM.patches.numX, ABM.patches.numY);
      } else {
        return u.radsToward(this.x, this.y, x, y);
      }
    };

    Agent.prototype.towards = function(o) {
      return this.towardsXY(o.x, o.y);
    };

    Agent.prototype.die = function() {
      var l, _i, _len, _ref;

      this.breed.remove(this);
      _ref = this.myLinks();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        l.die();
      }
      if (this.p.agents != null) {
        u.removeItem(this.p.agents, this);
      }
      return null;
    };

    Agent.prototype.hatch = function(num, breed, init) {
      var _this = this;

      if (num == null) {
        num = 1;
      }
      if (breed == null) {
        breed = ABM.agents;
      }
      if (init == null) {
        init = function() {};
      }
      return breed.create(num, function(a) {
        var k, v;

        a.setXY(_this.x, _this.y);
        for (k in _this) {
          if (!__hasProp.call(_this, k)) continue;
          v = _this[k];
          if (k !== "id") {
            a[k] = v;
          }
        }
        init(a);
        return a;
      });
    };

    Agent.prototype.inCone = function(aset, cone, radius, meToo) {
      if (meToo == null) {
        meToo = false;
      }
      return aset.inCone(this.p, this.heading, cone, radius, meToo);
    };

    Agent.prototype.otherEnd = function(l) {
      if (l.end1 === this) {
        return l.end2;
      } else {
        return l.end1;
      }
    };

    Agent.prototype.myLinks = function() {
      var l, _ref;

      return (_ref = this.links) != null ? _ref : (function() {
        var _i, _len, _ref1, _results;

        _ref1 = ABM.links;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          l = _ref1[_i];
          if ((l.end1 === this) || (l.end2 === this)) {
            _results.push(l);
          }
        }
        return _results;
      }).call(this);
    };

    Agent.prototype.linkNeighbors = function() {
      var l, _i, _len, _ref, _results;

      _ref = this.myLinks();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        _results.push(this.otherEnd(l));
      }
      return _results;
    };

    Agent.prototype.myInLinks = function() {
      var l, _i, _len, _ref, _results;

      _ref = this.myLinks();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        if (l.end2 === this) {
          _results.push(l);
        }
      }
      return _results;
    };

    Agent.prototype.inLinkNeighbors = function() {
      var l, _i, _len, _ref, _results;

      _ref = this.myLinks();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        if (l.end2 === this) {
          _results.push(l.end1);
        }
      }
      return _results;
    };

    Agent.prototype.myOutLinks = function() {
      var l, _i, _len, _ref, _results;

      _ref = this.myLinks();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        if (l.end1 === this) {
          _results.push(l);
        }
      }
      return _results;
    };

    Agent.prototype.outLinkNeighbors = function() {
      var l, _i, _len, _ref, _results;

      _ref = this.myLinks();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        if (l.end1 === this) {
          _results.push(l.end2);
        }
      }
      return _results;
    };

    return Agent;

  })();

  ABM.Agents = (function(_super) {
    __extends(Agents, _super);

    function Agents() {
      Agents.__super__.constructor.apply(this, arguments);
      this.useSprites = false;
    }

    Agents.prototype.cacheLinks = function() {
      return ABM.Agent.prototype.cacheLinks = true;
    };

    Agents.prototype.setDefaultColor = function(color) {
      return this.agentClass.prototype.color = color;
    };

    Agents.prototype.setDefaultShape = function(shape) {
      return this.agentClass.prototype.shape = shape;
    };

    Agents.prototype.setDefaultSize = function(size) {
      return this.agentClass.prototype.size = size;
    };

    Agents.prototype.setDefaultHeading = function(heading) {
      return this.agentClass.prototype.heading = heading;
    };

    Agents.prototype.setDefaultHidden = function(hidden) {
      return this.agentClass.prototype.hidden = hidden;
    };

    Agents.prototype.setDefaultSprite = function(sprite) {
      this.setDefaultColor(sprite.color);
      this.setDefaultShape(sprite.shape);
      this.setDefaultSize(sprite.size);
      return this.agentClass.prototype.sprite = sprite;
    };

    Agents.prototype.setDefaultPen = function(size, down) {
      if (down == null) {
        down = false;
      }
      this.agentClass.prototype.penSize = size;
      return this.agentClass.prototype.penDown = down;
    };

    Agents.prototype.setUseSprites = function(useSprites) {
      this.useSprites = useSprites != null ? useSprites : true;
    };

    Agents.prototype["in"] = function(array) {
      var o;

      return this.asSet((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = array.length; _i < _len; _i++) {
          o = array[_i];
          if (o.breed === this) {
            _results.push(o);
          }
        }
        return _results;
      }).call(this));
    };

    Agents.prototype.create = function(num, init) {
      var i, _i, _results;

      if (init == null) {
        init = function() {};
      }
      _results = [];
      for (i = _i = 1; _i <= num; i = _i += 1) {
        _results.push((function(o) {
          init(o);
          return o;
        })(this.add(new this.agentClass)));
      }
      return _results;
    };

    Agents.prototype.clear = function() {
      while (this.any()) {
        this.last().die();
      }
      return null;
    };

    Agents.prototype.inPatches = function(patches) {
      var array, p, _i, _len;

      array = [];
      for (_i = 0, _len = patches.length; _i < _len; _i++) {
        p = patches[_i];
        array.push.apply(array, p.agentsHere());
      }
      if (this.mainSet != null) {
        return this["in"](array);
      } else {
        return this.asSet(array);
      }
    };

    Agents.prototype.inRect = function(a, dx, dy, meToo) {
      var rect;

      if (meToo == null) {
        meToo = false;
      }
      rect = ABM.patches.patchRect(a.p, dx, dy, true);
      rect = this.inPatches(rect);
      if (!meToo) {
        u.removeItem(rect, a);
      }
      return rect;
    };

    Agents.prototype.inCone = function(a, heading, cone, radius, meToo) {
      var as;

      if (meToo == null) {
        meToo = false;
      }
      as = this.inRect(a, radius, radius, true);
      return as.inCone(a, heading, cone, radius, meToo);
    };

    Agents.prototype.inRadius = function(a, radius, meToo) {
      var as;

      if (meToo == null) {
        meToo = false;
      }
      as = this.inRect(a, radius, radius, true);
      return as.inRadius(a, radius, meToo);
    };

    return Agents;

  })(ABM.AgentSet);

  ABM.Link = (function() {
    Link.prototype.breed = null;

    Link.prototype.color = [130, 130, 130];

    Link.prototype.thickness = 2;

    Link.prototype.hidden = false;

    function Link(end1, end2) {
      this.end1 = end1;
      this.end2 = end2;
      if (this.end1.links != null) {
        this.end1.links.push(this);
        this.end2.links.push(this);
      }
    }

    Link.prototype.draw = function(ctx) {
      var pt;

      ctx.save();
      ctx.strokeStyle = u.colorStr(this.color);
      ctx.lineWidth = ABM.patches.bits2Patches(this.thickness);
      ctx.beginPath();
      if (!ABM.patches.isTorus) {
        ctx.moveTo(this.end1.x, this.end1.y);
        ctx.lineTo(this.end2.x, this.end2.y);
      } else {
        pt = this.end1.torusPt(this.end2);
        ctx.moveTo(this.end1.x, this.end1.y);
        ctx.lineTo.apply(ctx, pt);
        if (pt[0] !== this.end2.x || pt[1] !== this.end2.y) {
          pt = this.end2.torusPt(this.end1);
          ctx.moveTo(this.end2.x, this.end2.y);
          ctx.lineTo.apply(ctx, pt);
        }
      }
      ctx.closePath();
      ctx.stroke();
      return ctx.restore();
    };

    Link.prototype.die = function() {
      this.breed.remove(this);
      if (this.end1.links != null) {
        u.removeItem(this.end1.links, this);
      }
      if (this.end2.links != null) {
        u.removeItem(this.end2.links, this);
      }
      return null;
    };

    Link.prototype.bothEnds = function() {
      return [this.end1, this.end2];
    };

    Link.prototype.length = function() {
      return this.end1.distance(this.end2);
    };

    Link.prototype.otherEnd = function(a) {
      if (this.end1 === a) {
        return this.end2;
      } else {
        return this.end1;
      }
    };

    return Link;

  })();

  ABM.Links = (function(_super) {
    __extends(Links, _super);

    function Links() {
      Links.__super__.constructor.apply(this, arguments);
    }

    Links.prototype.setDefaultColor = function(color) {
      return this.agentClass.prototype.color = color;
    };

    Links.prototype.setDefaultThickness = function(thickness) {
      return this.agentClass.prototype.thickness = thickness;
    };

    Links.prototype.setDefaultHidden = function(hidden) {
      return this.agentClass.prototype.hidden = hidden;
    };

    Links.prototype.create = function(from, to, init) {
      var a, _i, _len, _results;

      if (init == null) {
        init = function() {};
      }
      if (to.length == null) {
        to = [to];
      }
      _results = [];
      for (_i = 0, _len = to.length; _i < _len; _i++) {
        a = to[_i];
        _results.push((function(o) {
          init(o);
          return o;
        })(this.add(new this.agentClass(from, a))));
      }
      return _results;
    };

    Links.prototype.clear = function() {
      while (this.any()) {
        this.last().die();
      }
      return null;
    };

    Links.prototype.allEnds = function() {
      var l, n, _i, _len;

      n = this.asSet([]);
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        l = this[_i];
        n.push(l.end1, l.end2);
      }
      return n;
    };

    Links.prototype.nodes = function() {
      return this.allEnds().sortById().uniq();
    };

    Links.prototype.layoutCircle = function(list, radius, startAngle, direction) {
      var a, dTheta, i, _i, _len;

      if (startAngle == null) {
        startAngle = Math.PI / 2;
      }
      if (direction == null) {
        direction = -1;
      }
      dTheta = 2 * Math.PI / list.length;
      for (i = _i = 0, _len = list.length; _i < _len; i = ++_i) {
        a = list[i];
        a.setXY(0, 0);
        a.heading = startAngle + direction * dTheta * i;
        a.forward(radius);
      }
      return null;
    };

    return Links;

  })(ABM.AgentSet);

  ABM.Animator = (function() {
    function Animator(model, rate, multiStep) {
      this.model = model;
      this.rate = rate != null ? rate : 30;
      this.multiStep = multiStep != null ? multiStep : false;
      this.animateDraws = __bind(this.animateDraws, this);
      this.animateSteps = __bind(this.animateSteps, this);
      this.ticks = this.draws = 0;
      this.animHandle = this.timerHandle = this.intervalHandle = null;
      this.animStop = true;
    }

    Animator.prototype.setRate = function(rate, multiStep) {
      this.rate = rate;
      this.multiStep = multiStep != null ? multiStep : false;
      return this.reset();
    };

    Animator.prototype.start = function() {
      if (!this.animStop) {
        return;
      }
      this.reset();
      this.animStop = false;
      return this.animate();
    };

    Animator.prototype.reset = function() {
      this.startMS = this.now();
      this.startTick = this.ticks;
      return this.startDraw = this.draws;
    };

    Animator.prototype.stop = function() {
      this.animStop = true;
      if (this.animHandle != null) {
        cancelAnimFrame(this.animHandle);
      }
      if (this.timeoutHandle != null) {
        clearTimeout(this.timeoutHandle);
      }
      if (this.intervalHandle != null) {
        clearInterval(this.intervalHandle);
      }
      return this.animHandle = this.timerHandle = this.intervalHandle = null;
    };

    Animator.prototype.step = function() {
      this.ticks++;
      return this.model.step();
    };

    Animator.prototype.draw = function() {
      this.draws++;
      return this.model.draw();
    };

    Animator.prototype.once = function() {
      this.step();
      return this.draw();
    };

    Animator.prototype.now = function() {
      return (typeof performance !== "undefined" && performance !== null ? performance : Date).now();
    };

    Animator.prototype.ms = function() {
      return this.now() - this.startMS;
    };

    Animator.prototype.ticksPerSec = function() {
      var elapsed;

      if ((elapsed = this.ticks - this.startTick) === 0) {
        return 0;
      } else {
        return Math.round(elapsed * 1000 / this.ms());
      }
    };

    Animator.prototype.drawsPerSec = function() {
      var elapsed;

      if ((elapsed = this.draws - this.startDraw) === 0) {
        return 0;
      } else {
        return Math.round(elapsed * 1000 / this.ms());
      }
    };

    Animator.prototype.toString = function() {
      return "ticks: " + this.ticks + ", draws: " + this.draws + ", rate: " + this.rate + " " + (this.ticksPerSec()) + "/" + (this.drawsPerSec());
    };

    Animator.prototype.animateSteps = function() {
      this.step();
      if (!this.animStop) {
        return this.timeoutHandle = setTimeout(this.animateSteps, 10);
      }
    };

    Animator.prototype.animateDraws = function() {
      if (this.drawsPerSec() <= this.rate) {
        if (!this.multiStep) {
          this.step();
        }
        this.draw();
      }
      if (!this.animStop) {
        return this.animHandle = requestAnimFrame(this.animateDraws);
      }
    };

    Animator.prototype.animate = function() {
      if (this.multiStep) {
        this.animateSteps();
      }
      return this.animateDraws();
    };

    return Animator;

  })();

  ABM.Model = (function() {
    Model.prototype.contextsInit = {
      patches: {
        z: 0,
        ctx: "2d"
      },
      drawing: {
        z: 1,
        ctx: "2d"
      },
      links: {
        z: 2,
        ctx: "2d"
      },
      agents: {
        z: 3,
        ctx: "2d"
      },
      spotlight: {
        z: 4,
        ctx: "2d"
      }
    };

    function Model(div, size, minX, maxX, minY, maxY, isTorus, hasNeighbors) {
      var beginVars, ctx, endVars, k, v, _ref;

      if (isTorus == null) {
        isTorus = true;
      }
      if (hasNeighbors == null) {
        hasNeighbors = true;
      }
      ABM.model = this;
      ABM.world = this.world = {
        div: div,
        size: size,
        minX: minX,
        maxX: maxX,
        minY: minY,
        maxY: maxY,
        isTorus: isTorus,
        hasNeighbors: hasNeighbors
      };
      this.contexts = ABM.contexts = {};
      _ref = this.contextsInit;
      for (k in _ref) {
        if (!__hasProp.call(_ref, k)) continue;
        v = _ref[k];
        this.contexts[k] = ctx = u.createLayer(div, size * (maxX - minX + 1), size * (maxY - minY + 1), v.z, v.ctx);
        ctx.save();
        ctx.scale(size, -size);
        ctx.translate(-(minX - .5), -(maxY + .5));
        ctx.agentSetName = k;
      }
      this.patches = ABM.patches = new ABM.Patches(ABM.Patch, "patches");
      this.agents = ABM.agents = new ABM.Agents(ABM.Agent, "agents");
      this.links = ABM.links = new ABM.Links(ABM.Link, "links");
      this.drawing = ABM.drawing = this.contexts.drawing;
      this.contexts.spotlight.globalCompositeOperation = "xor";
      this.anim = new ABM.Animator(this);
      this.refreshLinks = this.refreshAgents = this.refreshPatches = true;
      beginVars = (function() {
        var _results;

        _results = [];
        for (k in this) {
          if (!__hasProp.call(this, k)) continue;
          v = this[k];
          if (!((v.agentClass != null) || u.isFunction(v))) {
            _results.push(k);
          }
        }
        return _results;
      }).call(this);
      this.setup();
      endVars = (function() {
        var _results;

        _results = [];
        for (k in this) {
          if (!__hasProp.call(this, k)) continue;
          v = this[k];
          if (!((v.agentClass != null) || u.isFunction(v))) {
            _results.push(k);
          }
        }
        return _results;
      }).call(this);
      ABM.globals = this.globals = (function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = endVars.length; _i < _len; _i++) {
          v = endVars[_i];
          if (!u.contains(beginVars, v)) {
            _results.push(v);
          }
        }
        return _results;
      })();
      console.log("globals", this.globals);
    }

    Model.prototype.setFastPatches = function() {
      return this.patches.usePixels();
    };

    Model.prototype.setCacheAgentsHere = function() {
      return this.patches.cacheAgentsHere();
    };

    Model.prototype.setCacheMyLinks = function() {
      return this.agents.cacheLinks();
    };

    Model.prototype.setCachePatchRects = function(radius, meToo) {
      if (meToo == null) {
        meToo = false;
      }
      return this.patches.cacheRect(radius, meToo);
    };

    Model.prototype.agentSetCtxName = function(aset) {
      if (aset.mainSet != null) {
        aset = aset.mainSet;
      }
      return aset.constructor.name.toLowerCase();
    };

    Model.prototype.setTextParams = function(agentSetName, domFont, align, baseline) {
      if (align == null) {
        align = "center";
      }
      if (baseline == null) {
        baseline = "middle";
      }
      if (typeof agentSetName !== "string") {
        agentSetName = this.agentSetCtxName(agentSetName);
      }
      if (this.contexts[agentSetName] == null) {
        u.error("setTextParams: " + this.agentSetName + " not fount.");
      }
      return u.ctxTextParams(this.contexts[agentSetName], domFont, align, baseline);
    };

    Model.prototype.setLabelParams = function(agentSetName, color, xy) {
      if (typeof agentSetName !== "string") {
        agentSetName = this.agentSetCtxName(agentSetName);
      }
      if (this.contexts[agentSetName] == null) {
        u.error("setLabelParams: " + this.agentSetName + " not fount.");
      }
      return u.ctxLabelParams(this.contexts[agentSetName], color, xy);
    };

    Model.prototype.setup = function() {};

    Model.prototype.step = function() {};

    Model.prototype.start = function() {
      return this.anim.start();
    };

    Model.prototype.stop = function() {
      return this.anim.stop();
    };

    Model.prototype.once = function() {
      return this.anim.once();
    };

    Model.prototype.draw = function() {
      if (this.refreshPatches || this.anim.draws === 1) {
        this.patches.draw(this.contexts.patches);
      }
      if (this.refreshLinks || this.anim.draws === 1) {
        this.links.draw(this.contexts.links);
      }
      if (this.refreshAgents || this.anim.draws === 1) {
        this.agents.draw(this.contexts.agents);
      }
      if (this.spotlightAgent != null) {
        return this.drawSpotlight(this.spotlightAgent, this.contexts.spotlight);
      }
    };

    Model.prototype.setSpotlight = function(spotlightAgent) {
      this.spotlightAgent = spotlightAgent;
      if (this.spotlightAgent == null) {
        return u.clearCtx(this.contexts.spotlight);
      }
    };

    Model.prototype.drawSpotlight = function(agent, ctx) {
      u.clearCtx(ctx);
      u.fillCtx(ctx, [0, 0, 0, 0.6]);
      ctx.beginPath();
      ctx.arc(agent.x, agent.y, 3, 0, 2 * Math.PI, false);
      return ctx.fill();
    };

    Model.prototype.createBreeds = function(s, agentClass, breedSet) {
      var Breed, b, breeds, c, _i, _len, _ref, _ref1;

      breeds = [];
      breeds.classes = {};
      breeds.sets = {};
      _ref = s.split(" ");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        b = _ref[_i];
        c = Breed = (function(_super) {
          __extends(Breed, _super);

          function Breed() {
            _ref1 = Breed.__super__.constructor.apply(this, arguments);
            return _ref1;
          }

          return Breed;

        })(agentClass);
        this[b] = new breedSet(c, b, agentClass.prototype.breed);
        breeds.push(this[b]);
        breeds.sets[b] = this[b];
        breeds.classes["" + b + "Class"] = c;
      }
      return breeds;
    };

    Model.prototype.patchBreeds = function(s) {
      return ABM.patchBreeds = this.createBreeds(s, ABM.Patch, ABM.Patches);
    };

    Model.prototype.agentBreeds = function(s) {
      return ABM.agentBreeds = this.createBreeds(s, ABM.Agent, ABM.Agents);
    };

    Model.prototype.linkBreeds = function(s) {
      return ABM.linkBreeds = this.createBreeds(s, ABM.Link, ABM.Links);
    };

    Model.prototype.asSet = function(a) {
      return ABM.AgentSet.asSet(a);
    };

    Model.prototype.setRootVars = function() {
      root.ps = this.patches;
      root.p0 = this.patches[0];
      root.as = this.agents;
      root.a0 = this.agents[0];
      root.ls = this.links;
      root.l0 = this.links[0];
      root.dr = this.drawing;
      root.u = ABM.util;
      root.sh = ABM.shapes;
      root.app = this;
      root.cs = this.contexts;
      root.ab = ABM.agentBreeds;
      root.lb = ABM.linkBreeds;
      root.an = this.anim;
      root.wd = this.world;
      root.gl = this.globals;
      root.root = root;
      return null;
    };

    return Model;

  })();

}).call(this);

/*
//@ sourceMappingURL=agentscript.map
*/
