// Generated by CoffeeScript 1.6.3
(function() {
  var AscDataSet, DataSet, ImageDataSet, u,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  u = ABM.util;

  ABM.DataSet = DataSet = (function() {
    DataSet.patchDataSet = function(name) {
      var p, ps;
      return new DataSet((ps = ABM.patches).numX, ps.numY, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = ps.length; _i < _len; _i++) {
          p = ps[_i];
          _results.push(p[name]);
        }
        return _results;
      })());
    };

    DataSet.importImageDataSet = function(name, fmt, f) {
      var ds;
      if (fmt == null) {
        fmt = 3;
      }
      ds = new ImageDataSet();
      u.importImage(name, function(img) {
        ds.parse(img);
        if (f != null) {
          return f(ds);
        }
      });
      return ds;
    };

    DataSet.importAscDataSet = function(name, f) {
      var ds;
      ds = new AscDataSet();
      u.xhrLoadFile(name, "text", function(response) {
        ds.parse(response);
        if (f != null) {
          return f(ds);
        }
      });
      return ds;
    };

    function DataSet(width, height, data) {
      if (width == null) {
        width = 0;
      }
      if (height == null) {
        height = 0;
      }
      if (data == null) {
        data = [];
      }
      this.useNearest = false;
      this.reset(width, height, data);
    }

    DataSet.prototype.reset = function(width, height, data) {
      this.width = width;
      this.height = height;
      this.data = data;
      if (data.length !== width * height) {
        u.error("DataSet: data array length error:\ndata.length: " + this.data.length + " width: " + this.width + " height: " + this.height);
      }
      return this;
    };

    DataSet.prototype.checkXY = function(x, y) {
      if (!((0 <= x && x <= this.width - 1) && (0 <= y && y <= this.height - 1))) {
        return u.error("x,y out of range: " + x + "," + y);
      }
    };

    DataSet.prototype.setSampler = function(useNearest) {
      this.useNearest = useNearest;
    };

    DataSet.prototype.sample = function(x, y) {
      if (this.useNearest) {
        return this.nearest(x, y);
      } else {
        return this.bilinear(x, y);
      }
    };

    DataSet.prototype.nearest = function(x, y) {
      return this.getXY(Math.round(x), Math.round(y));
    };

    DataSet.prototype.bilinear = function(x, y) {
      var dx, dy, f00, f01, f10, f11, i, w, x0, y0, _ref, _ref1, _ref2;
      this.checkXY(x, y);
      x0 = Math.floor(x);
      y0 = Math.floor(y);
      i = this.toIndex(x0, y0);
      w = this.width;
      x = x - x0;
      y = y - y0;
      dx = 1 - x;
      dy = 1 - y;
      f00 = this.data[i];
      f01 = (_ref = this.data[i + w]) != null ? _ref : 0;
      f10 = (_ref1 = this.data[++i]) != null ? _ref1 : 0;
      f11 = (_ref2 = this.data[i + w]) != null ? _ref2 : 0;
      return f00 * dx * dy + f10 * x * dy + f01 * dx * y + f11 * x * y;
    };

    DataSet.prototype.toIndex = function(x, y) {
      return x + y * this.width;
    };

    DataSet.prototype.toXY = function(i) {
      return [i % this.width, Math.floor(i / this.width)];
    };

    DataSet.prototype.getXY = function(x, y) {
      this.checkXY(x, y);
      return this.data[this.toIndex(x, y)];
    };

    DataSet.prototype.setXY = function(x, y, num) {
      this.checkXY(x, y);
      return this.data[this.toIndex(x, y)] = num;
    };

    DataSet.prototype.toString = function(p, sep) {
      var data, i, s, _i, _ref;
      if (p == null) {
        p = 2;
      }
      if (sep == null) {
        sep = ", ";
      }
      s = "width: " + this.width + " height: " + this.height + " data:";
      data = p < 0 ? this.data : u.aToFixed(this.data, p);
      for (i = _i = 0, _ref = this.height; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        s += "\n" + ("" + i + ": " + (data.slice(i * this.width, (i + 1) * this.width)));
      }
      return s.replace(/,/g, sep);
    };

    DataSet.prototype.toImage = function(gray, normalize, alpha) {
      var ctx, d, i, idata, j, max, norm, num, ta, _i, _len;
      if (gray == null) {
        gray = true;
      }
      if (normalize == null) {
        normalize = true;
      }
      if (alpha == null) {
        alpha = 255;
      }
      ctx = u.createCtx(this.width, this.height);
      idata = ctx.getImageData(0, 0, this.width, this.height);
      ta = idata.data;
      max = Math.pow(2, gray ? 8 : 24);
      norm = normalize ? u.normalize(this.data, 0, max - 0.000001) : (function() {
        var _i, _len, _ref, _results;
        _ref = this.data;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          d = _ref[_i];
          _results.push(u.clamp(Math.round(d), 0, max - 1));
        }
        return _results;
      }).call(this);
      for (i = _i = 0, _len = norm.length; _i < _len; i = ++_i) {
        num = norm[i];
        j = 4 * i;
        ta[j + 3] = alpha;
        if (gray) {
          ta[j] = ta[j + 1] = ta[j + 2] = Math.floor(num);
        } else {
          ta[j] = num >>> 16;
          ta[j + 1] = (num >> 8) & 0xff;
          ta[j + 2] = num & 0xff;
        }
      }
      ctx.putImageData(idata, 0, 0);
      return ctx.canvas;
    };

    DataSet.prototype.toDrawing = function(gray) {
      var img;
      if (gray == null) {
        gray = true;
      }
      ABM.patches.installDrawing((img = this.toImage(gray)));
      return img;
    };

    DataSet.prototype.toPatchColors = function(gray) {
      var img;
      if (gray == null) {
        gray = true;
      }
      ABM.patches.installColors((img = this.toImage(gray)));
      return img;
    };

    DataSet.prototype.toPatchVar = function(name) {
      var data, p;
      data = (function() {
        var _i, _len, _ref, _results;
        _ref = ABM.patches;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          p = _ref[_i];
          _results.push(p[name] = this.patchSample(p.x, p.y));
        }
        return _results;
      }).call(this);
      return new DataSet(ABM.patches.numX, ABM.patches.numY, data);
    };

    DataSet.prototype.coordSample = function(x, y, tlx, tly, w, h) {
      var xs, ys;
      xs = (x - tlx) * (this.width - 1) / w;
      ys = (tly - y) * (this.height - 1) / h;
      return this.sample(xs, ys);
    };

    DataSet.prototype.patchSample = function(px, py) {
      var w;
      w = ABM.world;
      return this.coordSample(px, py, w.minXcor, w.maxYcor, w.numX, w.numY);
    };

    DataSet.prototype.resample = function(width, height) {
      var data, x, xScale, xs, y, yScale, ys, _i, _j;
      if (width === this.width && height === this.height) {
        return new DataSet(width, height, this.data);
      }
      data = [];
      xScale = (this.width - 1) / (width - 1);
      yScale = (this.height - 1) / (height - 1);
      for (y = _i = 0; _i < height; y = _i += 1) {
        for (x = _j = 0; _j < width; x = _j += 1) {
          xs = x * xScale;
          ys = y * yScale;
          data.push(this.sample(xs, ys));
        }
      }
      return new DataSet(width, height, data);
    };

    DataSet.prototype.neighborhood = function(x, y, array) {
      var dx, dy, x0, y0, _i, _j;
      if (array == null) {
        array = [];
      }
      array.length = 0;
      for (dy = _i = -1; _i <= 1; dy = ++_i) {
        for (dx = _j = -1; _j <= 1; dx = ++_j) {
          x0 = u.clamp(x + dx, 0, this.width - 1);
          y0 = u.clamp(y + dy, 0, this.height - 1);
          array.push(this.data[this.toIndex(x0, y0)]);
        }
      }
      return array;
    };

    DataSet.prototype.convolve = function(kernel, factor) {
      var array, n, x, y, _i, _j, _ref, _ref1;
      if (factor == null) {
        factor = 1;
      }
      array = [];
      n = [];
      for (y = _i = 0, _ref = this.height; _i < _ref; y = _i += 1) {
        for (x = _j = 0, _ref1 = this.width; _j < _ref1; x = _j += 1) {
          this.neighborhood(x, y, n);
          array.push(u.aSum(u.aPairMul(kernel, n)) * factor);
        }
      }
      return new DataSet(this.width, this.height, array);
    };

    DataSet.prototype.slopeAndAspect = function(cellsize, posRadians) {
      var aspect, dzdx, dzdy, gx, gy, rad, slope, x, y, _i, _j, _ref, _ref1;
      if (cellsize == null) {
        cellsize = 1;
      }
      if (posRadians == null) {
        posRadians = false;
      }
      dzdx = this.convolve([-1, 0, 1, -2, 0, 2, -1, 0, 1], 1 / 8);
      dzdy = this.convolve([1, 2, 1, 0, 0, 0, -1, -2, -1], 1 / 8);
      aspect = [];
      slope = [];
      for (y = _i = 0, _ref = this.height; _i < _ref; y = _i += 1) {
        for (x = _j = 0, _ref1 = this.width; _j < _ref1; x = _j += 1) {
          gx = dzdx.getXY(x, y);
          gy = dzdy.getXY(x, y);
          slope.push(Math.atan(Math.sqrt(gx * gx + gy * gy) / cellsize));
          rad = (gx === gy && gy === 0) ? NaN : Math.atan2(-gy, -gx);
          if (posRadians && rad < 0) {
            rad += 2 * Math.PI;
          }
          aspect.push(rad);
        }
      }
      slope = new DataSet(this.width, this.height, slope);
      aspect = new DataSet(this.width, this.height, aspect);
      return [slope, aspect, dzdx, dzdy];
    };

    DataSet.prototype.subset = function(x, y, width, height) {
      var data, i, j, _i, _j, _ref, _ref1;
      if (x + width > this.width || y + height > this.height) {
        u.error("subSet: params out of range");
      }
      data = [];
      for (j = _i = y, _ref = y + height; _i < _ref; j = _i += 1) {
        for (i = _j = x, _ref1 = x + width; _j < _ref1; i = _j += 1) {
          data.push(this.getXY(i, j));
        }
      }
      return new DataSet(width, height, data);
    };

    return DataSet;

  })();

  ABM.AscDataSet = AscDataSet = (function(_super) {
    __extends(AscDataSet, _super);

    function AscDataSet(str) {
      this.str = str != null ? str : "";
      AscDataSet.__super__.constructor.call(this);
      if (this.str.length === 0) {
        return;
      }
      this.parse(this.str);
    }

    AscDataSet.prototype.parse = function(str) {
      var i, keyVal, nums, textData, _i, _j, _k, _ref, _ref1;
      this.str = str;
      textData = str.split("\n");
      this.header = {};
      for (i = _i = 0; _i <= 5; i = ++_i) {
        keyVal = textData[i].split(/\s+/);
        this.header[keyVal[0].toLowerCase()] = parseFloat(keyVal[1]);
      }
      for (i = _j = 0, _ref = this.header.nrows; _j < _ref; i = _j += 1) {
        nums = textData[6 + i].trim().split(" ");
        for (i = _k = 0, _ref1 = nums.length; 0 <= _ref1 ? _k < _ref1 : _k > _ref1; i = 0 <= _ref1 ? ++_k : --_k) {
          nums[i] = parseFloat(nums[i]);
        }
        this.data = this.data.concat(nums);
      }
      return this.reset(this.header.ncols, this.header.nrows, this.data);
    };

    return AscDataSet;

  })(DataSet);

  ABM.ImageDataSet = ImageDataSet = (function(_super) {
    __extends(ImageDataSet, _super);

    function ImageDataSet(img, byteFmt) {
      this.img = img;
      this.byteFmt = byteFmt != null ? byteFmt : 3;
      ImageDataSet.__super__.constructor.call(this);
      if (this.img == null) {
        return;
      }
      this.parse(this.img);
    }

    ImageDataSet.prototype.ByteFmts = [[2], [1, 2], [0, 1, 2], [3, 0, 1, 2]];

    ImageDataSet.prototype.checkByteFmt = function() {
      var _ref;
      if (u.isArray(this.byteFmt)) {
        if (this.byteFmt.length > 4 || u.aMax(this.byteFmt) > 3 || u.aMin(this.byteFmt) < 0) {
          return u.error("bad ImageDataSet byte format array: " + this.byteFmt);
        }
      } else {
        if ((_ref = this.byteFmt) !== 1 && _ref !== 2 && _ref !== 3 && _ref !== 4 && _ref !== 8 && _ref !== 16 && _ref !== 24 && _ref !== 32) {
          u.error("bad ImageDataSet byte/bit format int: " + this.byteFmt);
        }
        if (this.byteFmt > 4) {
          this.byteFmt = this.byteFmt / 8;
        }
        return this.byteFmt = this.ByteFmts[this.byteFmt - 1];
      }
    };

    ImageDataSet.prototype.parse = function(img) {
      var i, j, ta, val, _i, _j, _len, _ref, _ref1;
      this.img = img;
      this.checkByteFmt(this.byteFmt);
      this.ctx = u.imageToCtx(this.img);
      ta = u.ctxToImageData(this.ctx).data;
      for (i = _i = 0, _ref = ta.length; _i < _ref; i = _i += 4) {
        val = 0;
        _ref1 = this.byteFmt;
        for (_j = 0, _len = _ref1.length; _j < _len; _j++) {
          j = _ref1[_j];
          val = val * 256 + ta[i + j];
        }
        this.data.push(val);
      }
      return this.reset(this.ctx.canvas.width, this.ctx.canvas.height, this.data);
    };

    return ImageDataSet;

  })(DataSet);

}).call(this);

/*
//@ sourceMappingURL=data.map
*/
